import { useCallback, useEffect, useRef, useState } from 'react'
import type { Editor } from '@tiptap/react'

/** A formatting suggestion generated by the autonomous scanner. */
export interface ScannerSuggestion {
  /** Unique key for React lists (node position + format). */
  key: string
  /** The formatting action to apply (e.g. 'heading1', 'heading2', 'bold'). */
  format: string
  /** Confidence score 0–100. */
  confidence: number
  /** ProseMirror doc position of the target node's start. */
  from: number
  /** ProseMirror doc position of the target node's end. */
  to: number
  /** 1-indexed page number the target appears on. */
  pageNumber: number
  /** Plain text preview of the target node. */
  preview: string
}

/**
 * Named states for the scanner state machine.
 * Matches the spec's core flow:
 * Idle_Scanning → OffScreen_Detected / InViewport_Detected → Accepted / Rejected / Dismissed
 */
export type ScannerState =
  | 'Idle_Scanning'
  | 'OffScreen_Detected'
  | 'InViewport_Detected'
  | 'Accepted'
  | 'Rejected'
  | 'Dismissed'

/** How often the scanner runs (ms). */
const SCAN_INTERVAL_MS = 10_000

/** Idle time after an editor change before a fresh sweep is scheduled (ms). */
const RESCAN_DEBOUNCE_MS = 1_500

/** How many heading-pattern lines to check per scan cycle. */
const MAX_SCAN_NODES = 30

/** Regex patterns that indicate heading-like content. */
const HEADING_PATTERNS: Array<{ re: RegExp; format: string; confidence: number }> = [
  { re: /^(chapter|abstract|introduction|conclusion|references|bibliography|appendix|acknowledgment)\s*[:.]?\s*$/i, format: 'heading1', confidence: 95 },
  { re: /^(section|part)\s+\d+/i, format: 'heading1', confidence: 92 },
  { re: /^\d+\.\s+[A-Z]/, format: 'heading1', confidence: 90 },
  { re: /^\d+\.\d+\s+/, format: 'heading2', confidence: 88 },
  { re: /^\d+\.\d+\.\d+\s+/, format: 'heading3', confidence: 85 },
  { re: /^[IVX]+\.\s+[A-Z]/, format: 'heading1', confidence: 88 },
  { re: /^(background|methodology|results|discussion|summary|related work|literature review|problem statement|objectives|scope)\s*[:.]?\s*$/i, format: 'heading2', confidence: 80 },
]

interface UseAutoFormatScannerOptions {
  editor: Editor | null
  enabled?: boolean
  /** Minimum confidence (0–1) a candidate must exceed to be suggested. */
  minConfidence?: number
}

/**
 * Autonomous document-wide formatting scanner.
 *
 * Implements the spec's state machine:
 * Idle_Scanning → OffScreen_Detected → InViewport_Detected → Accepted / Rejected
 *                                                   ↕ scroll
 *                                         OffScreen_Detected
 */
export function useAutoFormatScanner({
  editor,
  enabled = true,
  minConfidence = 0.68,
}: UseAutoFormatScannerOptions): {
  suggestions: ScannerSuggestion[]
  activeSuggestion: ScannerSuggestion | null
  scannerState: ScannerState
  isTargetInViewport: boolean
  dismissSuggestion: (key: string) => void
  dismissAll: () => void
  selectSuggestion: (key: string) => void
  acceptSuggestion: (key: string) => void
  rejectSuggestion: (key: string) => void
} {
  const [suggestions, setSuggestions] = useState<ScannerSuggestion[]>([])
  const [activeIdx, setActiveIdx] = useState<number>(-1)
  const [isTargetInViewport, setIsTargetInViewport] = useState<boolean>(true)
  const [scannerState, setScannerState] = useState<ScannerState>('Idle_Scanning')

  const scanTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const dismissedRef = useRef<Set<string>>(new Set())

  const activeSuggestion = activeIdx >= 0 && activeIdx < suggestions.length ? suggestions[activeIdx] : null

  /** Estimate which page a ProseMirror position falls on. */
  const estimatePageNumber = useCallback(
    (pos: number): number => {
      if (!editor || editor.isDestroyed) return 1
      let pageBreaks = 0
      editor.state.doc.nodesBetween(0, pos, (node) => {
        if (node.type.name === 'pageBreak' || (node.isBlock && node.type.name === 'horizontalRule')) {
          pageBreaks++
        }
      })
      if (pageBreaks > 0) return pageBreaks + 1
      // Fallback: character-ratio heuristic
      const docSize = editor.state.doc.content.size
      const ratio = docSize > 0 ? pos / docSize : 0
      const estimatedPages = Math.max(1, Math.ceil(docSize / 4000))
      return Math.min(Math.max(1, Math.round(ratio * estimatedPages) + 1), estimatedPages)
    },
    [editor]
  )

  /** Scan the document for heading-eligible paragraphs. */
  const scanDocument = useCallback(async (): Promise<void> => {
    if (!editor || editor.isDestroyed || !enabled) return

    const doc = editor.state.doc
    const candidates: ScannerSuggestion[] = []

    doc.descendants((node, pos) => {
      if (candidates.length >= MAX_SCAN_NODES) return false
      if (node.type.name !== 'paragraph' && node.type.name !== 'heading') return

      const text = node.textContent.trim()
      if (text.length < 4 || text.length > 150) return

      // Skip content that should never be suggested as a heading:
      // list items, table cells, questions, and questionnaire options.
      const $res = doc.resolve(pos)
      for (let d = $res.depth; d >= 0; d--) {
        const name = $res.node(d).type.name
        if (
          name === 'bulletList' || name === 'orderedList' || name === 'listItem' ||
          name === 'table' || name === 'tableRow' || name === 'tableCell' || name === 'tableHeader'
        ) {
          return
        }
      }
      if (/[?？]\s*$/.test(text)) return
      if (/^[a-dA-D][.)]\s/.test(text)) return

      for (const { re, format, confidence } of HEADING_PATTERNS) {
        if (re.test(text)) {
          if (confidence / 100 < minConfidence) continue
          if (node.type.name === 'heading') {
            const level = node.attrs.level as number
            const fmtNum = parseInt(format.replace('heading', ''), 10)
            if (level === fmtNum) return
          }

          const key = `${pos}:${format}`
          if (!dismissedRef.current.has(key)) {
            candidates.push({
              key,
              format,
              confidence,
              from: pos,
              to: pos + node.nodeSize,
              pageNumber: estimatePageNumber(pos),
              preview: text.slice(0, 60),
            })
          }
          break
        }
      }
      return true
    })

    candidates.sort((a, b) => b.confidence - a.confidence)
    setSuggestions(candidates)

    setActiveIdx((prev) => {
      if (prev < 0 && candidates.length > 0) return 0
      if (prev >= candidates.length) return candidates.length > 0 ? 0 : -1
      return prev
    })
  }, [editor, enabled, estimatePageNumber, minConfidence])

  /** Transition scanner state based on viewport and active suggestion. */
  useEffect(() => {
    if (!activeSuggestion) {
      setScannerState('Idle_Scanning')
      return
    }

    const view = editor?.view
    if (!view || view.isDestroyed) {
      setScannerState('Idle_Scanning')
      return
    }

    const coords = view.coordsAtPos(activeSuggestion.from)
    const viewportTop = window.scrollY
    const viewportBottom = window.scrollY + window.innerHeight
    const MARGIN = 120
    const inView =
      coords.bottom >= viewportTop - MARGIN &&
      coords.top <= viewportBottom + MARGIN

    setIsTargetInViewport(inView)
    setScannerState(inView ? 'InViewport_Detected' : 'OffScreen_Detected')
  }, [activeSuggestion, editor])

  /** Re-check viewport on scroll so off-screen targets correctly transition. */
  useEffect(() => {
    if (!activeSuggestion || !editor || editor.isDestroyed) return

    let ticking = false
    const onScroll = (): void => {
      if (ticking) return
      ticking = true
      requestAnimationFrame(() => {
        const view = editor.view
        if (view.isDestroyed) { ticking = false; return }
        const coords = view.coordsAtPos(activeSuggestion.from)
        const viewportTop = window.scrollY
        const viewportBottom = window.scrollY + window.innerHeight
        const MARGIN = 120
        const inView =
          coords.bottom >= viewportTop - MARGIN &&
          coords.top <= viewportBottom + MARGIN
        setIsTargetInViewport(inView)
        setScannerState(inView ? 'InViewport_Detected' : 'OffScreen_Detected')
        ticking = false
      })
    }

    window.addEventListener('scroll', onScroll, { passive: true })
    onScroll()
    return () => window.removeEventListener('scroll', onScroll)
  }, [activeSuggestion, editor])

  /** Schedule periodic scanning. */
  useEffect(() => {
    if (!enabled || !editor) return

    const initialTimer = setTimeout(() => {
      void scanDocument()
    }, 3000)

    scanTimerRef.current = setInterval(() => {
      void scanDocument()
    }, SCAN_INTERVAL_MS)

    return () => {
      clearTimeout(initialTimer)
      if (scanTimerRef.current) clearInterval(scanTimerRef.current)
    }
  }, [editor, enabled, scanDocument])

  // Re-sweep shortly after any document edit (accept/reject/typing) so the
  // next suggestion surfaces without waiting for the next interval tick.
  useEffect(() => {
    if (!enabled || !editor) return

    let debounceTimer: ReturnType<typeof setTimeout> | null = null
    const onTransaction = (): void => {
      if (debounceTimer) clearTimeout(debounceTimer)
      debounceTimer = setTimeout(() => {
        void scanDocument()
      }, RESCAN_DEBOUNCE_MS)
    }

    editor.on('transaction', onTransaction)
    return () => {
      if (debounceTimer) clearTimeout(debounceTimer)
      editor.off('transaction', onTransaction)
    }
  }, [editor, enabled, scanDocument])

  /** Dismiss a single suggestion (user clicked Ignore). */
  const dismissSuggestion = useCallback((key: string): void => {
    setScannerState('Dismissed')
    dismissedRef.current.add(key)
    setSuggestions((prev) => prev.filter((s) => s.key !== key))
    setActiveIdx((prev) => {
      if (prev < 0) return prev
      return 0
    })
    // After state transition, reset to Idle_Scanning for the next suggestion
    setTimeout(() => setScannerState('Idle_Scanning'), 0)
  }, [])

  /** Accept the current suggestion. */
  const acceptSuggestion = useCallback((key: string): void => {
    setScannerState('Accepted')
    dismissedRef.current.add(key)
    setSuggestions((prev) => prev.filter((s) => s.key !== key))
    setActiveIdx((prev) => {
      if (prev < 0) return prev
      return 0
    })
    setTimeout(() => setScannerState('Idle_Scanning'), 0)
  }, [])

  /** Reject the current suggestion. */
  const rejectSuggestion = useCallback((key: string): void => {
    setScannerState('Rejected')
    dismissedRef.current.add(key)
    setSuggestions((prev) => prev.filter((s) => s.key !== key))
    setActiveIdx((prev) => {
      if (prev < 0) return prev
      return 0
    })
    setTimeout(() => setScannerState('Idle_Scanning'), 0)
  }, [])

  /** Dismiss all current suggestions. */
  const dismissAll = useCallback((): void => {
    setScannerState('Dismissed')
    setSuggestions((prev) => {
      for (const s of prev) dismissedRef.current.add(s.key)
      return []
    })
    setActiveIdx(-1)
    setTimeout(() => setScannerState('Idle_Scanning'), 0)
  }, [])

  /** Select a specific suggestion by key. */
  const selectSuggestion = useCallback(
    (key: string): void => {
      const idx = suggestions.findIndex((s) => s.key === key)
      if (idx >= 0) setActiveIdx(idx)
    },
    [suggestions]
  )

  return {
    suggestions,
    activeSuggestion,
    scannerState,
    isTargetInViewport,
    dismissSuggestion,
    dismissAll,
    selectSuggestion,
    acceptSuggestion,
    rejectSuggestion,
  }
}
